# Generated by Django 5.2.1 on 2025-05-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Category')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of publication')),
                ('source', models.URLField(blank=True, verbose_name='Source')),
            ],
            options={
                'verbose_name': 'News',
            },
        ),
    ]
