# Generated by Django 5.2.1 on 2025-05-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of publication')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='chat_id')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
