# Generated by Django 5.2.1 on 2025-05-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
    ]
