# Generated by Django 5.2.1 on 2025-05-19 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.userdata')),
            ],
            options={
                'unique_together': {('user', 'news')},
            },
        ),
    ]
